"""refactor_status_model

Revision ID: 7cbeeb0a4f7b
Revises: f7a147bc0410
Create Date: 2026-07-04 14:43:34.744868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7cbeeb0a4f7b'
down_revision: Union[str, None] = 'f7a147bc0410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('video_jobs', sa.Column('current_step', sa.String(length=50), nullable=True, server_default='download'))
    op.add_column('video_jobs', sa.Column('review_state', sa.String(length=50), nullable=False, server_default='none'))
    op.add_column('video_jobs', sa.Column('stage_progress', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'stage_progress')
    op.drop_column('video_jobs', 'review_state')
    op.drop_column('video_jobs', 'current_step')
    # ### end Alembic commands ###
