"""add_srt_review_fields

Revision ID: f7a147bc0410
Revises: 011
Create Date: 2026-07-04 14:41:22.628661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7a147bc0410'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('transcript_srt_path', sa.Text(), nullable=True))
    op.add_column('video_jobs', sa.Column('transcript_text_path', sa.Text(), nullable=True))
    op.add_column('video_jobs', sa.Column('transcript_review_status', sa.String(length=20), nullable=True))
    op.add_column('video_jobs', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'reviewed_at')
    op.drop_column('video_jobs', 'transcript_review_status')
    op.drop_column('video_jobs', 'transcript_text_path')
    op.drop_column('video_jobs', 'transcript_srt_path')
    # ### end Alembic commands ###
